### ISSUE TITLE
Linker error when building MinitaurSDK with makefile from kodlab_gazebo

### ISSUE THREAD

**Issue by nikolaif399** [KodlabPenn/kodlab_gazebo#16]
Attempting to build the MinitaurSDK with the makefile from this repository (18.04, Melodic) is giving me a linker error. The error message suggest rebuilding libgazebo.a with -fPIC, but these libraries are precompiled in the SDK. Have you run into this issue/know of a way to mitigate it?

**Comment by vvasilo** [comment]
This is probably a question for Ghost - I don't know what the current status of the SDK is. Regardless, you could use the simulation by directly publishing torques to the actuator topics. Hope that helps!

**Comment by mailman2018** [comment]
Thanks! I was able to find a fix for the issue. I have a slightly modified Makefile that works in melodic, I can submit a PR if desired.

**Comment by nikolaif399** [comment]
Thanks! I was able to find a fix for the problem in melodic. I have a branch with the updated Makefile, do you want me to submit a pull request to this repo?

**Comment by vvasilo** [comment]
Absolutely, go for it! Thanks!
